# Generated by Django 6.0.3 on 2026-04-10 02:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('detallesId', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedidoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
    ]
