# Generated by Django 4.1 on 2026-04-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('detallesId', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedidoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.UniqueConstraint(fields=('pedidoId', 'productoId'), name='unique_producto_por_pedido'),
        ),
    ]
