# Generated by Django 6.0.3 on 2026-04-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_pedido', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='productoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='productos.producto'),
        ),
    ]
