# Generated by Django 4.1 on 2026-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
