# Generated by Django 4.1 on 2026-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dirección', models.CharField(max_length=100)),
                ('teléfono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
